### ISSUE TITLE
 403 FORBIDDEN (OpenURI::HTTPError)

### ISSUE THREAD

**Issue by psarossy** [astevens/factorio-mod-updater#1]
Trying to upgrade my mods on 0.15.15 on ubuntu nad getting this:

```
factorio@factorio:/opt/factorio$ /opt/factorio-mod-updater/factorio-mod-updater
Checking AfraidOfTheDark, AutoDeconstruct, autofill, Bottleneck, EvoGUI, Flare Stack, Flow Control, KBlueprints, long-reach, research-queue, Squeak Through, tree_collision, upgrade-planner, ZRecycling
Connecting to mods.factorio.com
AfraidOfTheDark by binbinhfr 1.0.16
        Current
AutoDeconstruct by mindmix 0.1.8
        Current
autofill by Nexela 1.4.8
        Current
Bottleneck by trold 0.7.3
        Installing
/usr/lib/ruby/2.3.0/open-uri.rb:359:in `open_http': 403 FORBIDDEN (OpenURI::HTTPError)
        from /usr/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
        from /usr/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
        from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
        from /usr/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
        from /usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
        from /usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
        from /usr/lib/ruby/2.3.0/open-uri.rb:31:in `open'
        from /opt/factorio-mod-updater/factorio-mod-updater:25:in `download'
        from /opt/factorio-mod-updater/factorio-mod-updater:85:in `block in <main>'
        from /opt/factorio-mod-updater/factorio-mod-updater:76:in `each'
        from /opt/factorio-mod-updater/factorio-mod-updater:76:in `<main>'
```

**Comment by psarossy** [comment]
Found the issue, you don't have to log in to run a headless server, so the token is not set.
Maybe add that to the documentation?
